apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: nginx
        image: nginx:latest